package com.hersis.activitytracker.view;

import com.hersis.activitytracker.controler.Controller;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Igor Rodriguez <igorrodriguezelvira@gmail.com>
 */
public class BackupDialog extends javax.swing.JDialog implements Observer{
	private final Controller controller;
	private final BackupRestoreDialog backupRestoreDialog;
	private final DateFormat backupDateFormat = new SimpleDateFormat("yyyy MMM dd, HH:mm:ss");
	
	/**
	 * Creates new form BackupDialog
	 */
	public BackupDialog(java.awt.Frame parent, boolean modal, Controller controller) {
		super(parent, modal);
		this.controller = controller;
		backupRestoreDialog = new BackupRestoreDialog(parent, true);
		initComponents();
		Controller.addPropertiesObserver(this);
		setBackupDateLabel();
	}
	
	private void setBackupDateLabel() {
		lblBackupDate.setText(backupDateFormat.format(Controller.getLastBackupDate().getTime()));
		this.pack();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        backupPanel = new javax.swing.JPanel();
        lblBackupDateMessage = new javax.swing.JLabel();
        lblBackupDate = new javax.swing.JLabel();
        btnBackupNow = new javax.swing.JButton();
        btnRestore = new javax.swing.JButton();
        btnConfigure = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        separatorPanel = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Backup");

        backupPanel.setLayout(new java.awt.GridBagLayout());

        lblBackupDateMessage.setText("Last backup date: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 0);
        backupPanel.add(lblBackupDateMessage, gridBagConstraints);

        lblBackupDate.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        lblBackupDate.setText("Unknown");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 5, 0, 7);
        backupPanel.add(lblBackupDate, gridBagConstraints);

        btnBackupNow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hersis/activitytracker/images/backup_64.png"))); // NOI18N
        btnBackupNow.setText("Backup now");
        btnBackupNow.setToolTipText("Backup now");
        btnBackupNow.setPreferredSize(new java.awt.Dimension(250, 60));
        btnBackupNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupNowActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        backupPanel.add(btnBackupNow, gridBagConstraints);

        btnRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hersis/activitytracker/images/backup_restore_64.png"))); // NOI18N
        btnRestore.setText("Restore");
        btnRestore.setToolTipText("Restore backup");
        btnRestore.setPreferredSize(new java.awt.Dimension(250, 60));
        btnRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        backupPanel.add(btnRestore, gridBagConstraints);

        btnConfigure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hersis/activitytracker/images/configure.png"))); // NOI18N
        btnConfigure.setText("Backup settings...");
        btnConfigure.setToolTipText("Backup settings");
        btnConfigure.setPreferredSize(new java.awt.Dimension(250, 42));
        btnConfigure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigureActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 10, 7);
        backupPanel.add(btnConfigure, gridBagConstraints);

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        separatorPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        buttonPanel.add(separatorPanel, gridBagConstraints);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hersis/activitytracker/images/button_cancel.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.setToolTipText(null);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        buttonPanel.add(btnClose, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 7, 7, 7);
        backupPanel.add(buttonPanel, gridBagConstraints);

        getContentPane().add(backupPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void btnRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreActionPerformed
		backupRestoreDialog.loadBackupValues();
		backupRestoreDialog.setLocationRelativeTo(this);
		backupRestoreDialog.setVisible(true);
	}//GEN-LAST:event_btnRestoreActionPerformed

	private void btnBackupNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupNowActionPerformed
		controller.startBackup(this);
	}//GEN-LAST:event_btnBackupNowActionPerformed

	private void btnConfigureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigureActionPerformed
		controller.showBackupConfigWindow();
	}//GEN-LAST:event_btnConfigureActionPerformed

	private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
		controller.closeBackupWindow();
	}//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backupPanel;
    private javax.swing.JButton btnBackupNow;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnConfigure;
    private javax.swing.JButton btnRestore;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel lblBackupDate;
    private javax.swing.JLabel lblBackupDateMessage;
    private javax.swing.JPanel separatorPanel;
    // End of variables declaration//GEN-END:variables

	@Override
	public void update(Observable o, Object arg) {
		setBackupDateLabel();
	}
}
