package com.hersis.activitytracker.view;

import com.hersis.activitytracker.controler.Controller;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author Igor Rodriguez <igorrodriguezelvira@gmail.com>
 */
public class MainForm extends javax.swing.JFrame {
	Controller controller;
	/**
	 * Creates new form MainForm
	 */
	public MainForm(Controller controller) {
		this.controller = controller;
		initComponents();
		init();
	}

	private void init() {
		this.addWindowListener(
				new WindowAdapter() {
					@Override
					public void windowClosing(WindowEvent e) {
						controller.exit();
					}
				});
	}
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNewActivity = new javax.swing.JButton();
        btnNewTime = new javax.swing.JButton();
        btnViewActivities = new javax.swing.JButton();
        btnViewTimes = new javax.swing.JButton();
        btnBackup = new javax.swing.JButton();
        btnOptions = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniBackup = new javax.swing.JMenuItem();
        mniOptions = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mniNewActivity = new javax.swing.JMenuItem();
        mniNewTime = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniViewActivities = new javax.swing.JMenuItem();
        mniViewTimes = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mniAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnNewActivity.setText("Nueva act");
        btnNewActivity.setFocusable(false);
        btnNewActivity.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewActivity.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnNewActivity);

        btnNewTime.setText("Nuevo tiempo");
        btnNewTime.setFocusable(false);
        btnNewTime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewTime.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnNewTime);

        btnViewActivities.setText("Ver act");
        btnViewActivities.setFocusable(false);
        btnViewActivities.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewActivities.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnViewActivities);

        btnViewTimes.setText("Ver tiempo");
        btnViewTimes.setFocusable(false);
        btnViewTimes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewTimes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnViewTimes);

        btnBackup.setText("Backup");
        btnBackup.setFocusable(false);
        btnBackup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBackup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnBackup);

        btnOptions.setText("Opciones");
        btnOptions.setFocusable(false);
        btnOptions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOptions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnOptions);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        mnuFile.setText("Archivo");

        mniBackup.setText("Backup");
        mnuFile.add(mniBackup);

        mniOptions.setText("Opciones...");
        mnuFile.add(mniOptions);
        mnuFile.add(jSeparator1);

        mniExit.setText("Salir");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniExit);

        jMenuBar1.add(mnuFile);

        mnuEdit.setText("Edicion");

        mniNewActivity.setText("Nueva actividad");
        mnuEdit.add(mniNewActivity);

        mniNewTime.setText("Nuevo tiempo");
        mnuEdit.add(mniNewTime);
        mnuEdit.add(jSeparator2);

        mniViewActivities.setText("Ver actividades");
        mnuEdit.add(mniViewActivities);

        mniViewTimes.setText("Ver tiempos");
        mnuEdit.add(mniViewTimes);

        jMenuBar1.add(mnuEdit);

        mnuHelp.setText("Ayuda");

        mniAbout.setText("Acerca de...");
        mnuHelp.add(mniAbout);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
		controller.exit();
	}//GEN-LAST:event_mniExitActionPerformed

	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnNewActivity;
    private javax.swing.JButton btnNewTime;
    private javax.swing.JButton btnOptions;
    private javax.swing.JButton btnViewActivities;
    private javax.swing.JButton btnViewTimes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mniAbout;
    private javax.swing.JMenuItem mniBackup;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniNewActivity;
    private javax.swing.JMenuItem mniNewTime;
    private javax.swing.JMenuItem mniOptions;
    private javax.swing.JMenuItem mniViewActivities;
    private javax.swing.JMenuItem mniViewTimes;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuHelp;
    // End of variables declaration//GEN-END:variables
}
