package com.hersis.activitytracker.view;

/**
 *
 * @author Igor Rodriguez <igorrodriguezelvira@gmail.com>
 */
public class ProgressBarDialog extends javax.swing.JDialog {
	
	/**
	 * Creates new modal form ProgressBarDialog
	 */
	public ProgressBarDialog(java.awt.Frame parent) {
		super(parent, true);
		initComponents();
		this.setLocationRelativeTo(parent);
	}
	
//	public void callInit() {
//		initComponents();
//	}

	public void setTaskTitle(String title) {
		progressBarPanel.setTaskTitle(title);
	}
	
	public String getTaskTitle() {
		return progressBarPanel.getTaskTitle();
	}
	
	public void setWaitMessage(String message) {
		progressBarPanel.setWaitMessage(message);
	}
	
	public String getWaitMessage() {
		return progressBarPanel.getWaitMessage();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBarPanel = new com.hersis.activitytracker.view.aux.ProgressBarPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(7, 7));
        getContentPane().add(progressBarPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hersis.activitytracker.view.aux.ProgressBarPanel progressBarPanel;
    // End of variables declaration//GEN-END:variables
}
