/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hersis.activitytracker.view;

/**
 *
 * @author Igor Rodriguez <igorrodriguezelvira@gmail.com>
 */
public class TimerPanel extends javax.swing.JPanel {

	/**
	 * Creates new form TimerPanel
	 */
	public TimerPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cmbActivities = new javax.swing.JComboBox();
        btnStart = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        txtStartTime = new javax.swing.JTextField();
        lblStartTime = new javax.swing.JLabel();
        lblPausedAt = new javax.swing.JLabel();
        lblTotalTime = new javax.swing.JLabel();
        txtPausedAt = new javax.swing.JTextField();
        txtTotalTime = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 10, 7);
        add(cmbActivities, gridBagConstraints);

        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hersis/activitytracker/images/player_play.png"))); // NOI18N
        btnStart.setText("Play");
        btnStart.setPreferredSize(new java.awt.Dimension(140, 58));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 7, 7, 5);
        add(btnStart, gridBagConstraints);

        btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hersis/activitytracker/images/player_pause.png"))); // NOI18N
        btnPause.setText("Pause");
        btnPause.setPreferredSize(new java.awt.Dimension(140, 58));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 5, 7, 5);
        add(btnPause, gridBagConstraints);

        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hersis/activitytracker/images/player_stop.png"))); // NOI18N
        btnStop.setText("Stop");
        btnStop.setPreferredSize(new java.awt.Dimension(140, 58));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 5, 7, 7);
        add(btnStop, gridBagConstraints);

        txtStartTime.setEditable(false);
        txtStartTime.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtStartTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStartTime.setText("16");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 5, 0, 7);
        add(txtStartTime, gridBagConstraints);

        lblStartTime.setText("Hora de inicio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 5);
        add(lblStartTime, gridBagConstraints);

        lblPausedAt.setText("Pausado en:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 5);
        add(lblPausedAt, gridBagConstraints);

        lblTotalTime.setText("Tiempo total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 5);
        add(lblTotalTime, gridBagConstraints);

        txtPausedAt.setEditable(false);
        txtPausedAt.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtPausedAt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPausedAt.setText("16");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 5, 0, 7);
        add(txtPausedAt, gridBagConstraints);

        txtTotalTime.setEditable(false);
        txtTotalTime.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtTotalTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalTime.setText("16");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 5, 0, 7);
        add(txtTotalTime, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JComboBox cmbActivities;
    private javax.swing.JLabel lblPausedAt;
    private javax.swing.JLabel lblStartTime;
    private javax.swing.JLabel lblTotalTime;
    private javax.swing.JTextField txtPausedAt;
    private javax.swing.JTextField txtStartTime;
    private javax.swing.JTextField txtTotalTime;
    // End of variables declaration//GEN-END:variables
}
